### ISSUE TITLE
Complete initial User Research Questionnaire

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#12]
**Objective**
Understand how our users interact with Twitter

**Description**
We are building a tool for twitter, and currently have no idea how our users interact with Twitter.

**Skills**

**Tools**
Stakeholder mapping

**Time Estimation**

**Tasks**

- [ ] Identify stakeholders -> politicians, feminist influencers across 5/7 European countries
- [ ] Work through the five stages of UX design
- [ ] Write questionnaire
- [ ] Identify channels they can be reached on -> APC (we already have some contacts so please ask)
- [ ] Prepare database/way of analysis for when the questionnaires are returned

**Comment by malteserteresa** [comment]
stakeholder mapping linked to issue #17

**Comment by malteserteresa** [comment]
Five stages to UX research. 

    1. Objectives: What are the knowledge gaps we need to fill?
    2. Hypotheses: What do we think we understand about our users? 
    3. Methods: Based on time and manpower, what methods should we select? 
    4. Conduct: Gather data through the selected methods. 
    5. Synthesize: Fill in the knowledge gaps, prove or disprove our hypotheses, and discover opportunities for our design efforts. 
    6. Feedback and editing

**Comment by malteserteresa** [comment]
Please see https://github.com/opt-out-tools/theory-of-online-misogyny/wiki/Twitter-User-Research and comment

**Comment by malteserteresa** [comment]
Being handled in issue https://github.com/opt-out-tools/website/issues/38
