### ISSUE TITLE
[WIP] Professional website design

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#16]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**
- [ ] Define Your Site’s Purpose and Strategy
- [ ] Research the Latest Web Design Trends & images 
- [ ] Design and developer session
- [ ] Add In and Optimize Your Content

**Comment by malteserteresa** [comment]
Purpose of website (initial):
- Inform about Opt Out why we exist
- Inform about our current understanding of problem space: our definition of misogyny
- Talk about the community
- Talk about our values
- Describe tools, how they work and our strategy
- Show demo of browser extension
- Reference other actors in this space, Iheartmob, take back the tech

Long-term purpose of website:
- Our KPIS
- More about current policy
- More about current tech efforts
- Transparency about our tech
- Ethics of AI for Opt Out
