### ISSUE TITLE
Questions to answer around Activism

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#20]
**Objective**

**Description**
What does the activism aspect of Opt Out look like? 
What content do we want for social media and how are we going to make it? L
What is the goal of the activism?
Examples:
Advocacy for an agreed definition of sexist harassment across EU member states
Pressuring Big Tech to take responsibility
Getting women into coding and STEM more generally
Encouraging self care and online hygiene
Creating a space for women to share experiences online (much like Everyday feminism)
Challenging patriarchal discourse (making noise and starting conversations)
Is it all of these things?
Do you envisage us partnering and collaborating with other organisations? IHeartMob have an app which supports reporting harassment - presumably building a data set themselves from this., ultimately, want us to be funded/absorbed by a big tech company?
Have you considered collaborating with Block Party or talking more with them rather than seeing them as competition? Is it an ideological difference or protecting the work that we’ve done so far? (I’m not too sure I understand!)
Where do we stand on online mediated Intimate Partner Violence? (I personally don’t think we’re able to stand anywhere on this at the moment, but I was wondering if you’d though about it?)
Have you thought any more about switching to a static website and then creating a mailing list off of that and requesting people answer a survey hosted through a third party website?

**Skills**
Campaigning, content writing, policy

**Tools**

**Time Estimation**

**Tasks**

- [ ] Decide on objectives of activism
- [ ] Decide on tone of activism
- [ ] Decide on methods and formats
