### ISSUE TITLE
Initial Marketing/Recruitment Campaign

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#25]
**Objective**
Get Opt Out Tools work known so we get fundraising and developers

**Description**
We need money and to build our open source community. 

**Skills**
Marketing
Content writing

**Tools**
Brand book

**Time Estimation**

**Tasks**
- [ ] Finish brand book
- [ ] Identify demographics
- [ ] Identify people to share
- [ ] Assign content writing tasks
- [ ] Build strategy
