### ISSUE TITLE
[WIP] Develop Roles for Opt Out Tools

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#27]
**Objective**
Decide on roles needed within Opt Out 

**Description**
Opt Out has reached over 10 people as it's core team spanning many different fields, thus we require some structure in order to work most efficiently. 

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Ensure future tasks are clearly defined
- [ ] Consider roles and research other organisational structures in this space
- [ ] Write a [constitution](https://github.com/CoMakery/self-organization-constitution)

**Comment by malteserteresa** [comment]
Current Non Tech Roles:

- Volunteer Manager

- Community building

- Fundraising + partnership

- Marketing + external

- User Advocates

**Comment by malteserteresa** [comment]
Not for us yet but interesting nontheless https://opensource.com/open-organization/18/4/silicon-valley-self-organizing-systems

**Comment by malteserteresa** [comment]
First three definitions:

**Maintainer**
Someone who feels responsibility over the direction of the project and is committed to improving it.

**Contributor**
Anyone who comments on an issue or pull request, people who add value to the project (whether it’s triaging issues, writing code, or organizing events), or anybody with a merged pull request (perhaps the narrowest definition of a contributor).

**Committer**
Someone who feels responsibility over the direction of the project and is committed to improving it and writes code.

Roles within Opt Out:
**Contributor Manager**
    • Helps new volunteers get started (onboarding) 
    • Maintains engagement with volunteers through regular meetings and social activities 
**Community Activist**
    • Helps recruit new volunteers and represent Opt Out at events 
    • Organises meetups, workshops & hackathons for the external community 

**Fundraising and Partnership Management**
    • Finds & researches funding opportunities; apply & write grants for these opportunities 
    • Finds & establishes relevant opportunities 

**Marketing  and External Engagement**
    • Writes and distributes newsletter (project updates, past and upcoming events, vacancies, relevant articles) 
    • Branding & social media presence 

**User Advocates**
    • Facilitate interaction between users and team
    •  Advocating for the user, and attempt to see the product through the eyes of, and the experience of, the user. 

**Event Design**
    • Designs and helps facilitate the hackathons, workshops or internal training

Looking forward:
**Mentor Manager**: we would like to have mentors for all female-identifying people contributing to the project one day. This would need to be managed
**Data Auditor**: checking and consulting with us on best practices wrt data provacy
**Ethics board**

**Comment by adrinjalali** [comment]
It's a pretty good start I'd say. I feel like there are kinda way too many roles here. Quite a few of them can be merged. Of course later on when the project gets larger and busier, you can decide them.

On the coding side, AFAIK, the convention is that anyvody who contributes code, i.e. has a PR, is a contributor, people who are authorized to merge those PRs are maintainers, and people who can handle tags and labels and make sure questions are clear etc, are the triage team. I'd say for now you don't even need a triage team. That'll be needed with a busier repo.

You also have a few roles basically to mentor people to get in the project. That to me is every maintainer.

And about the general direction of the project, you can have a technical committee for instance, who's different than the maintainer team, but you could also rely on maintainers for now for that purpose.

Sort of same applies to non-coding roles IMO.

**Comment by adrinjalali** [comment]
You have assigned a whole bunch of us here, but I'm not sure what we're supposed to do :D

**Comment by malteserteresa** [comment]
Think, add/suggest roles. But this is labelled backlog and is thus a "slow-burner" of a task
