### ISSUE TITLE
Initial User Meeting

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#29]
**Objective**
To discuss future collaboration with the Association for Progressive Communication

**Description**
Meeting to plan the first release to users.

**Skills**

**Tools**

**Time Estimation**
1 hour

**Tasks**

- [ ] Discuss how to proceed with opt out browser extension testing
- [ ] How to promote the extension
- [ ] Talk about the Association for Progressive Communication members

**Comment by malteserteresa** [comment]
Here is a brief summary of topics discussed and next steps. Please feel free to add to this email.

Topics discussed
- Status & description of the browser extension
- Freedom of speech "boundary"
- Learning opportunity -> conflict between data protection, copyright and collaboration
- Reporting of the Tweets
- Which users to reach out to

Next steps:
Erika to put Teresa in contact with members of Deflect Canada?

Florie and Erika to test out the extension and see how it works in order to write a TBT Action.

To do this Teresa will:
- Write specific instructions how t install, including gentle git into
- Write guidelines on how to test

Aim to get this done for when Florie and Erika return from the Philippines.

I've also attached a gif of the browser extension in action, so you can get an idea of how it works.
