### ISSUE TITLE
Open soure qualitative research strategies on GitHub

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#30]
**Objective**
To decide how we can best use github to complete our qualitative research

**Description**
github is great for code, but we want to not only build software but document and display the information. Is there a way to do this on Github aside from the wikis?

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Research
- [ ] Decide initial strategy
- [ ] Try out
- [ ] Reflect and evaluate

**Comment by malteserteresa** [comment]
We have decided that background research will go into the wikis, our consolidated ideas as .md files.

Tasks still to complete
- [ ] How to disseminate the .md files work into the tech that we build?

Possibly by the bookclub and workshop ideas, but let's keep ideas juicy and flowing here on this issue!
