### ISSUE TITLE
[WIP] Discuss & Choose our Entity Type

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#34]
**Objective**
Make OOT into an NGO (verein) so we can apply for [EC funding](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/rec-rdap-gbv-ag-2020;freeTextSearchKeyword=;typeCodes=1;statusCodes=31094502;programCode=REC;programDivisionCode=null;focusAreaCode=null;crossCuttingPriorityCode=null;callCode=Default;sortQuery=openingDate;orderBy=asc;onlyTenders=false;topicListKey=topicSearchTablePageState)

**Description**

 1 .As a member of a Verein, you are not personally responsible if the Verein gets into debt or legal difficulties (unlike a GbR).
 2. It is possible to register a Verein as “Gemeinnützig” giving you charitable status and all of the donation-related tax benefits that entails.
3. It is quite cheap to found (no need for expensive legal fees).
4. You don’t need any capital to get started.

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Get your 7 founding members together
- [ ] Write a “Satzung” (Statutes) - this contains all the information about what the Verein is there for, how decisions are taken, becoming a member, member fees etc. Should follow a specific form and the Vereinszweck (mission) should be very clear. If you are planning on going for charitable status make sure you include all of the elements of the work you are planning to do, because the Finanzamt will check at the end of the year that you are doing what you said you would, and if you have been doing other stuff as well, they might take away your charitable status and make you pay taxes retrospectively. To help you we have included ours from back then, as lots of the formal stuff is applicable to all Vereine, so you can copy and adapt.
- [ ] Get together with your founding members for your first meeting, vote for the Vorstand (between 1 and 7 people - we had 3) and sign the “Satzung”.
- [ ] Make sure to keep notes and create minutes as the “Gründungsprotokoll” also needs to be attached and sent with the Satzung to the authorities.
- [ ] If you are planning on applying for charitable status, you should send your Satzung to the relevant Finanzamt first. They might want you to make some changes and you should do that before registering, otherwise you will have to pay to make changes once it is done. In Berlin the relevant Finanzamt is:

Finanzamt für Körperschaften I
Bredtschneiderstr. 5
14057 Berlin

You can send it in or if you have specific questions, make an appointment and bring it with you. Allow up to six weeks before it is cleared (this is optimistic).
- [ ] Take the above documents, with the rest of the Vorstand, to a notary (we went here: http://www.robe.org/arbeitsgebiete/notariat/). Again you will need the Satzung, Minutes from first meeting including names of all members present, identity documents for all of the Vorstand).
- [ ] Send all of the above to the Amtsgericht Charlottenburg (or your Notary will do it for you):

Amtsgerichtsplatz 1
14057 Berlin
Stadtplan

Tel: +49 (0)30 90177 0
Fax: +49 (0)30 90177 447
- [ ] Wait for the documentation - you will need this in order to open a bank account. (If you get the charitable status, some banks such as GLS waiver the banking fees)

**Comment by adrinjalali** [comment]
So we're going for the verein model and not an ug afterall?

**Comment by malteserteresa** [comment]
I think this would be faster and also I don't know how an .UG is recognised internationally

**Comment by malteserteresa** [comment]
Also we could always become an .UG later
