### ISSUE TITLE
Decide on team & milestones for Prototype fund Application

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#37]
**Objective**
We should decide on the team who wants to apply for the prototype fund.

**Description**
The prototype fund https://prototypefund.de/  funds open source projects. We need to decide on the team who would like to apply for it so we can begin the application.

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Research what the PF is and what they're looking for this round
- [ ] Form working group of interested people
- [ ] Decide on what would be covered
- [ ] Confirm team
