### ISSUE TITLE
Write Prototype Fund application

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#38]
**Objective**
Complete PF application

**Description**

**Skills**

**Tools**

**Time Estimation**
Deadline 31st March

**Tasks**

- [ ] Depends on https://github.com/opt-out-tools/start-here/issues/37
- [ ] Research 
- [ ] Write application in English
- [ ] Translate into German
