### ISSUE TITLE
Decide on team and milestones for MOSS grant

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#39]
**Objective**
Decide on team and milestones for MOSS grant

**Description**
MOSS grants are rolling application funding opportunities from Mozilla. We need to apply with the idea of internal communications moderation

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Review current application
- [ ] Decide on tasks
- [ ] Decide on team

[MOSS grant.pdf](https://github.com/opt-out-tools/start-here/files/4176901/MOSS.grant.pdf)
