### ISSUE TITLE
Write Privacy Policy

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#41]
**Objective**
Complete our privacy policy

**Description**
A privacy policy is a statement or a legal document (in privacy law) that discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client's data. It fulfills a legal requirement to protect a customer or client's privacy.

**Skills**
Legal

**Tools**

**Time Estimation**

**Tasks**

- [ ] Define scope of OOT
- [ ] Identify data streams
- [ ] Review for health or client confientiality requirements
