### ISSUE TITLE
Write data processing agreements

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#43]
**Objective**
Write data processing agreements with third party sites

**Description**
GDPR compliance requires data controllers to sign a data processing agreement with any parties that act as data processors on their behalf

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Identify third party companies
- [ ] Read about [data processing agreements](https://gdpr.eu/what-is-data-processing-agreement/) 
- [ ] Use [template](https://gdpr.eu/data-processing-agreement/)
