### ISSUE TITLE
Set Up Funding Page: https://opencollective.com/opt-out

### ISSUE THREAD

**Issue by jorgejativa** [opt-out-tools/start-here#45]
**Objective**
Update OSC website so ready for crowdfunding campaign

**Description**
We need to get the open collective website fit for the crowdfunding campaign. This includes content, budget, people handling expenses requests etc.

**Skills**

**Tools**
URL for the funding page is: https://opencollective.com/opt-out
Good example: https://opencollective.com/webpack
Relies on issue #44 

**Time Estimation**

**Tasks**

- [ ] Turn issue #44 into budget
- [ ] Add minutes to OSC page
- [ ] Get someone to review content on about

**Comment by Cheukting** [comment]
I can translate to the traditional Chinese

**Comment by malteserteresa** [comment]
Content we need to fill out for the crowdfunding page!

Open Source Collective Content:
About OOT
Event (IWD crowdfunding description)
Collective Goals (Funding and Our Vision)
Tiers (Types of backing)

**Comment by malteserteresa** [comment]
In review by Nikki :)
