### ISSUE TITLE
Set up content/social media plan for prelaunch

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#50]
**Objective**
Set up plan for content and social media strategy for prelaunch

**Description**
Prelaunch will happen before March 8th, letting people know about Opt Out Tools and what we are doing

**Skills**
Marketing

**Tools**
Depends on issue #49

**Time Estimation**

**Tasks**

- [ ] Get content created from issue #49
- [ ] Choose channels
- [ ] Complete insta stories #54 
- [ ] Create social media schedule
- [ ] Reach out to people to share

**Comment by malteserteresa** [comment]
Completed
