### ISSUE TITLE
Create content for prelaunch

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#55]
**Objective**
Create OOT story content for prelaunch

**Description**
This has already begun with Linkedin story but we need to add to it and decide where else we can share this. Also need to add crowdfunding link.

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Decide which platforms
- [ ] Decide if we need more content
- [ ] Set up schedule

**Comment by malteserteresa** [comment]
https://docs.google.com/document/d/1LNoltwfLqX1dv0nNTgeplA4cvQA_lXKTnH8EBi_O9Yo/edit?usp=sharing
